#Colocamos el lenguaje que vamos a usar
FROM golang:1.18.1

#Creamos el directorio de trabajo
WORKDIR /tarea2

#Copiamos el archivo
COPY . ./

#Descargamos las dependencias
RUN go mod download

#Exponemos el puerto
EXPOSE 3000

#Ejecutamos el archivo
CMD [ "go", "run", "main.go" ]